name: MCPB Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  mcpb-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Extract version from release
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "MCPB Release version: $VERSION"
        
    - name: Build MCPB Package
      run: |
        # Create bundle directory
        mkdir -p bundle
        cp index.js bundle/
        cp package.json bundle/
        
        # Install production dependencies
        cd bundle
        npm install --production
        
        # Create MCPB package
        npx @anthropic-ai/mcpb pack
        
